window.GALLERY_DATA = [
  {
    "no": 1,
    "file": "o001_BroniaFine_poppies.jpg",
    "title": "Poppies",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 2,
    "file": "o002_BroniaFine_naturmort.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 3,
    "file": "o003_BroniaFine_lilac.jpg",
    "title": "Lilac",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 4,
    "file": "o004_BroniaFine_autumn_leaves.jpg",
    "title": "Autumn Leaves",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 5,
    "file": "o005_BroniaFine_autumn_in_Romania.jpg",
    "title": "Autumn In Romania",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 6,
    "file": "o006_BroniaFine_autumn_in_Romania.jpg",
    "title": "Autumn In Romania",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 7,
    "file": "o007_BroniaFine_roses.jpg",
    "title": "Roses",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 8,
    "file": "o008_BroniaFine_lily_of_the_valleys.jpg",
    "title": "Lily Of The Valleys",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 9,
    "file": "o009_BroniaFine_field_of_flowers.jpg",
    "title": "Field Of Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 10,
    "file": "o010_BroniaFine_white_rose.jpg",
    "title": "White Rose",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 11,
    "file": "o011_BroniaFine_roses.jpg",
    "title": "Roses",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 12,
    "file": "o012_BroniaFine_Safed.jpg",
    "title": "Safed",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 13,
    "file": "o013_BroniaFine_Jerusalem_A.jpg",
    "title": "Jerusalem A",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 14,
    "file": "o014_BroniaFine_Jerusalem_B.jpg",
    "title": "Jerusalem B",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 15,
    "file": "o015_BroniaFine_Jerusalem_C.jpg",
    "title": "Jerusalem C",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 16,
    "file": "o016_BroniaFine_red_rose.jpg",
    "title": "Red Rose",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 17,
    "file": "o017_BroniaFine_Still_LIFE.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 18,
    "file": "o018_BroniaFine_Japan_lake.jpg",
    "title": "Japan Lake",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 19,
    "file": "o019_BroniaFine_Sakura.jpg",
    "title": "Sakura",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 20,
    "file": "o020_BroniaFine_Sunrise.jpg",
    "title": "Sunrise",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 21,
    "file": "o021_BroniaFine_autumn_leaves.jpg",
    "title": "Autumn Leaves",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 22,
    "file": "o022_BroniaFine_naturmort.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 23,
    "file": "o023_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 24,
    "file": "o024_BroniaFine_Georgia_Shatili.jpg",
    "title": "Georgia Shatili",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 25,
    "file": "o025_BroniaFine_Lifta-Jerusalem.jpg",
    "title": "Lifta Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 26,
    "file": "o026_BroniaFine_Cafe_Focaccia-Jerusalem.jpg",
    "title": "Cafe Focaccia Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 27,
    "file": "o027_BroniaFine_Montefiori_Jerusalem.jpg",
    "title": "Montefiori Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 28,
    "file": "o028_BroniaFine_basket_with_mushrooms.jpg",
    "title": "Basket With Mushrooms",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 29,
    "file": "o029_BroniaFine_Tower_of_David.jpg",
    "title": "Tower Of David",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 30,
    "file": "o030_BroniaFine_Spring_Shades.jpg",
    "title": "Spring Shades",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 31,
    "file": "o031_BroniaFine_winter_in_Slovakia.jpg",
    "title": "Winter In Slovakia",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 32,
    "file": "o035_BroniaFine_Magic_Garden.jpg",
    "title": "Magic Garden",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 33,
    "file": "o036_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 34,
    "file": "o037_BroniaFine_Raspberry_still_life.jpg",
    "title": "Raspberry Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 35,
    "file": "o038_BroniaFine_confederation_house.jpg",
    "title": "Confederation House",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 36,
    "file": "o039_BroniaFine_Lilies_on_the_river.jpg",
    "title": "Lilies On The River",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 37,
    "file": "o040_BroniaFine_Lilies_on_water.jpg",
    "title": "Lilies On Water",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 38,
    "file": "o041_BroniaFine_still_life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 39,
    "file": "o042_BroniaFine_pomegranates.jpg",
    "title": "Pomegranates",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 40,
    "file": "o043_BroniaFine_pomegranates.jpg",
    "title": "Pomegranates",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 41,
    "file": "o044_BroniaFine_autumn_in_Kiev.jpg",
    "title": "Autumn In Kiev",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 42,
    "file": "o045_BroniaFine_Masks_on_a_wall.jpg",
    "title": "Masks On A Wall",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 43,
    "file": "o046_BroniaFine_Lilies_on_water.jpg",
    "title": "Lilies On Water",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 44,
    "file": "o047_BroniaFine_Camels_on_Negev.jpg",
    "title": "Camels On Negev",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 45,
    "file": "o048_BroniaFine_still-life_with_pomegranates.jpg",
    "title": "Still Life With Pomegranates",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 46,
    "file": "o049_BroniaFine_Nachlaot_Jerusalem.jpg",
    "title": "Nachlaot Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 47,
    "file": "o050_BroniaFine_Birch_forest.jpg",
    "title": "Birch Forest",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 48,
    "file": "o051_BroniaFine_Venician_Masks.jpg",
    "title": "Venician Masks",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 49,
    "file": "o052_BroniaFine_winter_Piestany.jpg",
    "title": "Winter Piestany",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 50,
    "file": "o053_BroniaFine_Venician_Masks.jpg",
    "title": "Venician Masks",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 51,
    "file": "o054_BroniaFine_ROWAN_in_the_winter.jpg",
    "title": "Rowan In The Winter",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 52,
    "file": "o055_BroniaFine_IGUASSU_1.jpg",
    "title": "Iguassu 1",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 53,
    "file": "o055_BroniaFine_IGUASSU_2.jpg",
    "title": "Iguassu 2",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 54,
    "file": "o055_BroniaFine_IGUASSU_3.jpg",
    "title": "Iguassu 3",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 55,
    "file": "o055_BroniaFine_IGUASSU_triptych.jpg",
    "title": "Iguassu Triptych",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 56,
    "file": "o056_BroniaFine_Almonds_Branch.jpg",
    "title": "Almonds Branch",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 57,
    "file": "o057_BroniaFine_Ranunculus.jpg",
    "title": "Ranunculus",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 58,
    "file": "o058_BroniaFine_Dana_and_Sea.jpg",
    "title": "Dana And Sea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 59,
    "file": "o059_BroniaFine_Still_Life_with_vine.jpg",
    "title": "Still Life With Vine",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 60,
    "file": "o060_BroniaFine_Morning_in_Kibuch.jpg",
    "title": "Morning In Kibuch",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 61,
    "file": "o061_BroniaFine_Sun_down_in_Sishel_1.jpg",
    "title": "Sun Down In Sishel 1",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 62,
    "file": "o061_BroniaFine_Sun_down_in_Sishel_2.jpg",
    "title": "Sun Down In Sishel 2",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 63,
    "file": "o061_BroniaFine_Sun_down_in_Sishel_3.jpg",
    "title": "Sun Down In Sishel 3",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 64,
    "file": "o061_BroniaFine_Sun_down_in_Sishel_triptych.jpg",
    "title": "Sun Down In Sishel Triptych",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 65,
    "file": "o062_BroniaFine_Flamenco_dancer.jpg",
    "title": "Flamenco Dancer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 66,
    "file": "o063_BroniaFine_ballet_dancer.jpg",
    "title": "Ballet Dancer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 67,
    "file": "o064_BroniaFine_Sunset_in_Jerusalem.jpg",
    "title": "Sunset In Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 68,
    "file": "o065_BroniaFine_dancer.jpg",
    "title": "Dancer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 69,
    "file": "o066_BroniaFine_dreams_of_a_holiday_apartment.jpg",
    "title": "Dreams Of A Holiday Apartment",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 70,
    "file": "o067_BroniaFine_yellow_field.jpg",
    "title": "Yellow Field",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 71,
    "file": "o068_BroniaFine_Lake_with_Lilies.jpg",
    "title": "Lake With Lilies",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 72,
    "file": "o069_BroniaFine_lilac_bouquet_in_a_bucket.jpg",
    "title": "Lilac Bouquet In A Bucket",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 73,
    "file": "o070_BroniaFine_red_field.jpg",
    "title": "Red Field",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 74,
    "file": "o071_BroniaFine_cock.jpg",
    "title": "Cock",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 75,
    "file": "o072_BroniaFine_small_bridge.jpg",
    "title": "Small Bridge",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 76,
    "file": "o073_BroniaFine_cranes.jpg",
    "title": "Cranes",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 77,
    "file": "o074_BroniaFine_vineyard.jpg",
    "title": "Vineyard",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 78,
    "file": "o075_BroniaFine_violet_field.jpg",
    "title": "Violet Field",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 79,
    "file": "o076_BroniaFine_Jordane_river.jpg",
    "title": "Jordane River",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 80,
    "file": "o077_BroniaFine_yellow_flowers.jpg",
    "title": "Yellow Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 81,
    "file": "o078_BroniaFine_Jerusalem_Tiho_house.jpg",
    "title": "Jerusalem Tiho House",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 82,
    "file": "o079_BroniaFine_Winter_in_Jerusalem.jpg",
    "title": "Winter In Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 83,
    "file": "o080_BroniaFine_Almond_flowering.jpg",
    "title": "Almond Flowering",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 84,
    "file": "o081_BroniaFine_Art_fair.jpg",
    "title": "Art Fair",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 85,
    "file": "o082_BroniaFine_winter-in-jerusalen.jpg",
    "title": "Winter In Jerusalen",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 86,
    "file": "o083_BroniaFine_window_to_garden.jpg",
    "title": "Window To Garden",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 87,
    "file": "o084_BroniaFine_Jerusalem_Yemin_Moshe_st.jpg",
    "title": "Jerusalem Yemin Moshe St",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 88,
    "file": "o085_BroniaFine_balcony_in_flowers.jpg",
    "title": "Balcony In Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 89,
    "file": "o086_BroniaFine_Aylaon-road_Tel-aviv.jpg",
    "title": "Aylaon Road Tel Aviv",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 90,
    "file": "o087_BroniaFine_oak.jpg",
    "title": "Oak",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 91,
    "file": "o088_BroniaFine_ballet_bolshoi.jpg",
    "title": "Ballet Bolshoi",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 92,
    "file": "o089_BroniaFine_ballet_bolshoi.jpg",
    "title": "Ballet Bolshoi",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 93,
    "file": "o090_BroniaFine_ballet_bolshoi.jpg",
    "title": "Ballet Bolshoi",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 94,
    "file": "o091_BroniaFine_poppies_field.jpg",
    "title": "Poppies Field",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 95,
    "file": "o092_BroniaFine_Still_Life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 96,
    "file": "o093_BroniaFine_Swiss_Landscape.jpg",
    "title": "Swiss Landscape",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 97,
    "file": "o094_BroniaFine_raining_in_jerusalem_Jaffo_st.jpg",
    "title": "Raining In Jerusalem Jaffo St",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 98,
    "file": "o095_BroniaFine_window_to_garden.jpg",
    "title": "Window To Garden",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 99,
    "file": "o096_BroniaFine_roses.jpg",
    "title": "Roses",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 100,
    "file": "o097_BroniaFine_SEA_oil_70x50.jpg",
    "title": "Sea Oil 70X50",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 101,
    "file": "o098_BroniaFine_raining_in_Jerusalem_Jaffo_st-2.jpg",
    "title": "Raining In Jerusalem Jaffo St 2",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 102,
    "file": "o099_BroniaFine_old_city_Jerusalem.jpg",
    "title": "Old City Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 103,
    "file": "o100_BroniaFine_flowers_in_a_jug.jpg",
    "title": "Flowers In A Jug",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 104,
    "file": "o101_BroniaFine_vegetable_still_life.jpg",
    "title": "Vegetable Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 105,
    "file": "o102_BroniaFine_Boganvilia.jpg",
    "title": "Boganvilia",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 106,
    "file": "o103_BroniaFine_Still_Life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 107,
    "file": "o104_BroniaFine_tel-aviv.jpg",
    "title": "Tel Aviv",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 108,
    "file": "o105_BroniaFine_Hedera.jpg",
    "title": "Hedera",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 109,
    "file": "o106_BroniaFine_Western_wall.jpg",
    "title": "Western Wall",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 110,
    "file": "o107_BroniaFine_Old_City_Jerusalem.jpg",
    "title": "Old City Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 111,
    "file": "o108_BroniaFine_King_Gorge_HOTEL.jpg",
    "title": "King Gorge Hotel",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 112,
    "file": "o109_BroniaFine_flowers_in_a_jug.jpg",
    "title": "Flowers In A Jug",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 113,
    "file": "o110_BroniaFine_Old_Jerusalem.jpg",
    "title": "Old Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 114,
    "file": "o111_BroniaFine_Tul_Karem_Jerusalem.jpg",
    "title": "Tul Karem Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 115,
    "file": "o112_BroniaFine_flowers_under_walls_of_Jerusalem.jpg",
    "title": "Flowers Under Walls Of Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 116,
    "file": "o113_BroniaFine_Lilac_at_a_window.jpg",
    "title": "Lilac At A Window",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 117,
    "file": "o114_BroniaFine_St.John_Monastery_Israel.jpg",
    "title": "St.John Monastery Israel",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 118,
    "file": "o115_BroniaFine_summer_in_Sant_Peterburg.jpg",
    "title": "Summer In Sant Peterburg",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 119,
    "file": "o116_BroniaFine_roses_at_a_window.jpg",
    "title": "Roses At A Window",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 120,
    "file": "o117_BroniaFine_sea.jpg",
    "title": "Sea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 121,
    "file": "o118_BroniaFine_brige_Jerusalem.jpg",
    "title": "Brige Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 122,
    "file": "o119_BroniaFine_3-FAIRIES.jpg",
    "title": "3 Fairies",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 123,
    "file": "o120_BroniaFine_Jerusalem_tram.jpg",
    "title": "Jerusalem Tram",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 124,
    "file": "o121_BroniaFine_summer_wood.jpg",
    "title": "Summer Wood",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 125,
    "file": "o122_BroniaFine_Mahane-Jeuda.jpg",
    "title": "Mahane Jeuda",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 126,
    "file": "o123_BroniaFine_APPLES.jpg",
    "title": "Apples",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 127,
    "file": "o124_BroniaFine_MUSHROOMS.jpg",
    "title": "Mushrooms",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 128,
    "file": "o125_BroniaFine_The_women_with_a_mirror.jpg",
    "title": "The Women With A Mirror",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 129,
    "file": "o126_BroniaFine_Old_men_and_sea.jpg",
    "title": "Old Men And Sea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 130,
    "file": "o127_BroniaFine_family_and_sea.jpg",
    "title": "Family And Sea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 131,
    "file": "o128_BroniaFine_Russan_summer.jpg",
    "title": "Russan Summer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 132,
    "file": "o129_BroniaFine_Russan_summer.jpg",
    "title": "Russan Summer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 133,
    "file": "o130_BroniaFine_Russan_autumn.jpg",
    "title": "Russan Autumn",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 134,
    "file": "o131_BroniaFine_Budapest.jpg",
    "title": "Budapest",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 135,
    "file": "o132_BroniaFine_Jerusalem.jpg",
    "title": "Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 136,
    "file": "o133_1_BroniaFine_gerl.jpg",
    "title": "O133 1 Broniafine Girl",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 137,
    "file": "o133_BroniaFine_still_life_on_flank.jpg",
    "title": "Still Life On Flank",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 138,
    "file": "o134_BroniaFine_tea_drinking_on_scarf.jpg",
    "title": "Tea Drinking On Scarf",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 139,
    "file": "o135_BroniaFine_rural_still_life.jpg",
    "title": "Rural Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 140,
    "file": "o136_BroniaFine_violoncellist.jpg",
    "title": "Violoncellist",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 141,
    "file": "o137_BroniaFine_violinist.jpg",
    "title": "Violinist",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 142,
    "file": "o138_BroniaFine_zion_square.jpg",
    "title": "Zion Square",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 143,
    "file": "o139_BroniaFine_vaza_with_daisies.jpg",
    "title": "Vaza With Daisies",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 144,
    "file": "o140_BroniaFine_music_still_life.jpg",
    "title": "Music Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 145,
    "file": "o142_BroniaFine_winter_pond.jpg",
    "title": "Winter Pond",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 146,
    "file": "o143_BroniaFine_old_women_in_the_rain.jpg",
    "title": "Old Women In The Rain",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 147,
    "file": "o144_BroniaFine_still_life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 148,
    "file": "o145_BroniaFine_geese_over_Jerusalem.jpg",
    "title": "Geese Over Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 149,
    "file": "o146_BroniaFine_Jerusalem.jpg",
    "title": "Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 150,
    "file": "o147_BroniaFine_Eilat.jpg",
    "title": "Eilat",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 151,
    "file": "o148_BroniaFine_Jerusalem.jpg",
    "title": "Jerusalem",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 152,
    "file": "o149_BroniaFine_dancers.jpg",
    "title": "Dancers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 153,
    "file": "o150_BroniaFine_juffo_port.jpg",
    "title": "Juffo Port",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 154,
    "file": "o151_BroniaFine_Romi.jpg",
    "title": "Romi",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 155,
    "file": "o152_BroniaFine_Turkey.jpg",
    "title": "Turkey",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 156,
    "file": "o153_BroniaFine_Lilacs_in_a_vase.jpg",
    "title": "Lilacs In A Vase",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 157,
    "file": "o154_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 158,
    "file": "o155_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 159,
    "file": "o156_BroniaFine_runner.jpg",
    "title": "Runner",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 160,
    "file": "o157_BroniaFine_funny_elephants.jpg",
    "title": "Funny Elephants",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 161,
    "file": "o158_BroniaFine_country_house.jpg",
    "title": "Country House",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 162,
    "file": "o159_BroniaFine_still_life_with_bottles.jpg",
    "title": "Still Life With Bottles",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 163,
    "file": "o160_BroniaFine_old_women_on_roundabout.jpg",
    "title": "Old Women On Roundabout",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 164,
    "file": "o161_BroniaFine_Bruklin_bridge.jpg",
    "title": "Bruklin Bridge",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 165,
    "file": "o162_BroniaFine_Italy.jpg",
    "title": "Italy",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 166,
    "file": "o163_BroniaFine_windows.jpg",
    "title": "Windows",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 167,
    "file": "o164_BroniaFine_balkon.jpg",
    "title": "Balkon",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 168,
    "file": "o165_BroniaFine_danser_in_white.jpg",
    "title": "Danser In White",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 169,
    "file": "o166_BroniaFine_still_life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 170,
    "file": "o167_BroniaFine_women.jpg",
    "title": "Women",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 171,
    "file": "o168_BroniaFine_African.jpg",
    "title": "African",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 172,
    "file": "o169_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 173,
    "file": "o170_BroniaFine_MAYA_PLISECHKAYA.jpg",
    "title": "Maya Plisechkaya",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 174,
    "file": "o171_BroniaFine_Perugia.jpg",
    "title": "Perugia",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 175,
    "file": "o172_BroniaFine_Anna_Karenina.jpg",
    "title": "Anna Karenina",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 176,
    "file": "o173_BroniaFine_women_in_Paris.jpg",
    "title": "Women In Paris",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 177,
    "file": "o174_BroniaFine_women_in_Paris.jpg",
    "title": "Women In Paris",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 178,
    "file": "o175_BroniaFine_women.jpg",
    "title": "Women",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 179,
    "file": "o176_BroniaFine_Lia_buthday.jpg",
    "title": "Lia Buthday",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 180,
    "file": "o177_BroniaFine_guitar_player.jpg",
    "title": "Guitar Player",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 181,
    "file": "o178_BroniaFine_ballet_dancer.jpg",
    "title": "Ballet Dancer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 182,
    "file": "o179_BroniaFine_sea.jpg",
    "title": "Sea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 183,
    "file": "o180_BroniaFine_woman_in_N.Y.jpg",
    "title": "Woman In N.Y",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 184,
    "file": "o181_BroniaFine_Saxophonist.jpg",
    "title": "Saxophonist",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 185,
    "file": "o182_BroniaFine_kiss_in_N.Y.jpg",
    "title": "Kiss In N.Y",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 186,
    "file": "o183_BroniaFine_flowers.jpg",
    "title": "Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 187,
    "file": "o184_BroniaFine_Lion.jpg",
    "title": "Lion",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 188,
    "file": "o185_BroniaFine_YAFFO.jpg",
    "title": "Yaffo",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 189,
    "file": "o186_BroniaFine_CUBA.jpg",
    "title": "Cuba",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 190,
    "file": "o187_BroniaFine_WOMEN_AND_LEAFFALL.jpg",
    "title": "Women And Leaffall",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 191,
    "file": "o188_BroniaFine_girl_in_garden.jpg",
    "title": "Girl In Garden",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 192,
    "file": "o189_BroniaFine_by_the_fireplace.jpg",
    "title": "By The Fireplace",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 193,
    "file": "o190_BroniaFine_dancer.jpg",
    "title": "Dancer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 194,
    "file": "o191_BroniaFine_mystic_world.jpg",
    "title": "Mystic World",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 195,
    "file": "o192_BroniaFine_girl_with_dog.jpg",
    "title": "Girl With Dog",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 196,
    "file": "o193_BroniaFine_my_drims.jpg",
    "title": "My Drims",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 197,
    "file": "o194_BroniaFine_sisters.jpg",
    "title": "Sisters",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 198,
    "file": "o195_Girl_at_bar.jpg",
    "title": "O195 Girl At Bar",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 199,
    "file": "o196_Admiralty_in_lilac.jpg",
    "title": "O196 Admiralty In Lilac",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 200,
    "file": "o197_BroniaFine_Patagoniya.jpg",
    "title": "Patagoniya",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 201,
    "file": "o198_BroniaFine__Still_Life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 202,
    "file": "o199_BroniaFine__girl_and_flowers.jpg",
    "title": "Girl And Flowers",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 203,
    "file": "o200_BroniaFine__girl_in_the_window.jpg",
    "title": "Girl In The Window",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 204,
    "file": "o201_BroniaFine__Caravan.jpg",
    "title": "Caravan",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 205,
    "file": "o202_BroniaFine__Maidan_Tbilisi.jpg",
    "title": "Maidan Tbilisi",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 206,
    "file": "o203_BroniaFine__Olive_garden.jpg",
    "title": "Olive Garden",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 207,
    "file": "o205_BroniaFine__Girl_in_Paris.jpg",
    "title": "Girl In Paris",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 208,
    "file": "o206_BroniaFine__windows.jpg",
    "title": "Windows",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 209,
    "file": "o207_BroniaFine__windows.jpg",
    "title": "Windows",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 210,
    "file": "o208_BroniaFine__winter.jpg",
    "title": "Winter",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 211,
    "file": "o210_BroniaFine__tel-aviv.jpg",
    "title": "Tel Aviv",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 212,
    "file": "o211_BroniaFine__mother_with_child.jpg",
    "title": "Mother With Child",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 213,
    "file": "o212_BroniaFine__Vietnam.jpg",
    "title": "Vietnam",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 214,
    "file": "o213_BroniaFine_girl_in_leaves.jpg",
    "title": "Girl In Leaves",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 215,
    "file": "o214_BroniaFine_Horses_on_a_moonlit_night.jpg",
    "title": "Horses On A Moonlit Night",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 216,
    "file": "o215_BroniaFine_Lita.jpg",
    "title": "Lita",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 217,
    "file": "o216_BroniaFine_town.jpg",
    "title": "Town",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 218,
    "file": "o217_BroniaFine_toreador.jpg",
    "title": "Toreador",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 219,
    "file": "o218_BroniaFine_citi_in_bloom.jpg",
    "title": "Citi In Bloom",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 220,
    "file": "o219_BroniaFine_Girl_with_a glass.jpg",
    "title": "Girl With A Glass",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 221,
    "file": "o220_BroniaFine_Dana_in_Tailand.jpg",
    "title": "Dana In Tailand",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 222,
    "file": "o221_BroniaFine_Old_dacha.jpg",
    "title": "Old Dacha",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 223,
    "file": "o222_BroniaFine_GIRL.jpg",
    "title": "Girl",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 224,
    "file": "o223_BroniaFine_old_Singer.jpg",
    "title": "Old Singer",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 225,
    "file": "o224_BroniaFine_town.jpg",
    "title": "Town",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 226,
    "file": "o225_BroniaFine_girl_with _an_umbrella.jpg",
    "title": "Girl With An Umbrella",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 227,
    "file": "o226_BroniaFine_girl_with_hat.jpg",
    "title": "Girl With Hat",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 228,
    "file": "o227_BroniaFine_LINA.jpg",
    "title": "Lina",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 229,
    "file": "o228_BroniaFine_Holand.jpg",
    "title": "Holland",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 230,
    "file": "o229_BroniaFine_kichen.JPG",
    "title": "Kichen",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 231,
    "file": "o230_BroniaFine_Japan.jpg",
    "title": "Japan",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 232,
    "file": "o231_BroniaFine_still_life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 233,
    "file": "o232_BroniaFine_Afrika.JPG",
    "title": "Afrika",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 234,
    "file": "o233_BroniaFine_still-life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 235,
    "file": "o234_BroniaFine_gerl.jpg",
    "title": "Girl",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 236,
    "file": "o235_BroniaFine_old man.jpg",
    "title": "Old Man",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 237,
    "file": "o236_BroniaFine_veatnam.jpg",
    "title": "Veatnam",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 238,
    "file": "o237_BroniaFine_windows.jpg",
    "title": "Windows",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 239,
    "file": "o238_BroniaFine_still-life_ pomegranates.jpg",
    "title": "Still Life Pomegranates",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 240,
    "file": "o239_BroniaFine_dancers-gerles.jpg",
    "title": "Dancers Girles",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 241,
    "file": "o240_BroniaFine_still-life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 242,
    "file": "o241_BroniaFine_outumn.jpg",
    "title": "Autumn",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 243,
    "file": "o242_BroniaFine_still-life_ pomegranates.jpg",
    "title": "Still Life Pomegranates",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 244,
    "file": "o243_BroniaFine_dance.jpg",
    "title": "Dance",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 245,
    "file": "o244_BroniaFine_Amsterdam.jpg",
    "title": "Amsterdam",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 246,
    "file": "o245_BroniaFine_Girl.jpg",
    "title": "Girl",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 247,
    "file": "o246_BroniaFine_dance.jpg",
    "title": "Dance",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 248,
    "file": "o247_BroniaFine_dance.jpg",
    "title": "Dance",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 249,
    "file": "o248_BroniaFine_still_life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 250,
    "file": "o249_BroniaFine_gerl_with tea.jpg",
    "title": "Girl With Tea",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 251,
    "file": "o250_BroniaFine_Afrika.jpg",
    "title": "Afrika",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 252,
    "file": "o251_BroniaFine_Japanese_girl.jpg",
    "title": "Japanese Girl",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 253,
    "file": "o252_BroniaFine_old_men.jpg",
    "title": "Old Men",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 254,
    "file": "o253_BroniaFine_girl_at_the dacha.jpg",
    "title": "Girl At The Dacha",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 255,
    "file": "o254_BroniaFine_gerl_whith_child.jpg",
    "title": "Girl With Child",
    "year": "",
    "size": "50 × 70 cm",
    "medium": "Oil on canvas",
    "category": "Oil Paintings",
    "description": "",
    "status": "At Home"
  }
];
