window.GALLERY_DATA = [
  {
    "no": 1,
    "file": "w001_BroniaFine_Ukrainian_Autumn.jpg",
    "title": "Ukrainian Autumn",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 2,
    "file": "w002_BroniaFine_Seashore.jpg",
    "title": "Seashore",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 3,
    "file": "w003_BroniaFine_Hawaiian_Sunset.jpg",
    "title": "Hawaiian Sunset",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 4,
    "file": "w004_BroniaFine_Swiss_Landscape.jpg",
    "title": "Swiss Landscape",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 5,
    "file": "w005_BroniaFine_Alpine_winter.jpg",
    "title": "Alpine Winter",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 6,
    "file": "w006_BroniaFine_lake.jpg",
    "title": "Lake",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 7,
    "file": "w007_BroniaFine_Dutch_Landscape.jpg",
    "title": "Dutch Landscape",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 8,
    "file": "w008_BroniaFine_Switzeland.jpg",
    "title": "Switzerland",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 9,
    "file": "w009_BroniaFine_Provence.jpg",
    "title": "Provence",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 10,
    "file": "w010_BroniaFine_Alps.jpg",
    "title": "Alps",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 11,
    "file": "w011_BroniaFine_Switzeland.jpg",
    "title": "Switzerland",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 12,
    "file": "w012_BroniaFine_Montmartre.jpg",
    "title": "Montmartre",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 13,
    "file": "w013_BroniaFine_Switzeland.jpg",
    "title": "Switzerland",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 14,
    "file": "w014_BroniaFine_women-portrait.jpg",
    "title": "Women Portrait",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 15,
    "file": "w015_BroniaFine_Austria.jpg",
    "title": "Austria",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 16,
    "file": "w016_BroniaFine_Holand.jpg",
    "title": "Holland",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 17,
    "file": "w017_BroniaFine_Poppy_field.jpg",
    "title": "Poppy Field",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 18,
    "file": "w018_BroniaFine_Bouquet.jpg",
    "title": "Bouquet",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 19,
    "file": "w019_BroniaFine_Sill_Life.jpg",
    "title": "Still Life",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 20,
    "file": "w020_BroniaFine_old_city-Jerusalem.jpg",
    "title": "Old City Jerusalem",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 21,
    "file": "w021_BroniaFine_old_city-Jerusalem.jpg",
    "title": "Old City Jerusalem",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 22,
    "file": "w022_BroniaFine_Provence.jpg",
    "title": "Provence",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 23,
    "file": "w023_BroniaFine_River.jpg",
    "title": "River",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  },
  {
    "no": 24,
    "file": "w024_BroniaFine_Venezia.jpg",
    "title": "Venice",
    "year": "",
    "size": "",
    "medium": "Watercolor on paper",
    "category": "Watercolors",
    "description": "",
    "status": "At Home"
  }
];
